# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=200)),
                ('end_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.User')),
            ],
        ),
    ]
